<?php

use Drupal\Core\Render\Element;

function registration_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id)
{
    if (($form_id === 'user_register_form')) {
        $form['account']['name']['#description'] = 'This name will be used when registering for events and to identify any photos or posts created by you on the site.';
    }
}

/**
 * Implements hook_theme().
 */
function registration_theme() {
    return [
        'registration' => [
            'render element' => 'elements',
        ],
    ];
}

/**
 * Prepares variables for registration templates.
 *
 * Default template: registration.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the registration information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_registration(array &$variables) {
    $variables['view_mode'] = $variables['elements']['#view_mode'];
    foreach (Element::children($variables['elements']) as $key) {
        $variables['content'][$key] = $variables['elements'][$key];
    }
}
