<?php

use Drupal\Core\Render\Element;

function registration_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id)
{
    if (($form_id === 'registration_edit_form') || ($form_id === 'registration_add_form') || ($form_id === 'user_form')) {
        $form['uid']['widget'][0]['target_id']['#title'] = 'Registrant';
        $form['uid']['widget'][0]['target_id']['#description'] = 'The user who is registering for the event. (Not editable)';
    }
}

/**
 * Implements hook_theme().
 */
function registration_theme() {
    return [
        'registration' => [
            'render element' => 'elements',
        ],
    ];
}

/**
 * Prepares variables for registration templates.
 *
 * Default template: registration.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the registration information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_registration(array &$variables) {
    $variables['view_mode'] = $variables['elements']['#view_mode'];
    foreach (Element::children($variables['elements']) as $key) {
        $variables['content'][$key] = $variables['elements'][$key];
    }
}
